server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: metrics,health
    health:
      show-details: always

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: theatre-service
          uri: lb://THEATRE-SERVICE
          predicates:
            - Path=/theatre/**
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
        - id: show-service
          uri: lb://SHOW-SERVICE
          predicates:
            - Path=/show/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
          filters:
            - name: CircuitBreaker
              args:
                name: booking-service
                fallbackuri: forward:/fallback/booking
